export const userConstants = {
  USERS_LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  USERS_LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  USERS_LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  USERS_LOGOUT: 'USERS_LOGOUT',

  USERS_REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  USERS_REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  USERS_REGISTER_FAILURE: 'USERS_REGISTER_FAILURE'
};
